# Generated by Django 5.2.9 on 2026-01-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtbooking',
            name='court_name',
        ),
        migrations.AddField(
            model_name='courtbooking',
            name='court_number',
            field=models.IntegerField(choices=[(1, 'Court 1'), (2, 'Court 2'), (3, 'Court 3'), (4, 'Court 4')], default=1),
        ),
    ]
